### PR TITLE
Fix build with bison >= 3.7.5

### PR DESCRIPTION
**Pull request by foutrelis**
Fixes the following linker error:

```
/usr/bin/ld: kafel/libkafel.a(libkafel.o): in function `kafel_yyerror':
arm_syscalls.c:(.text+0x6984): undefined reference to `YYUSE'
```

### CODE REVIEW

File: src/parser.y [hunk 1]
```diff
@@ -418,10 +418,9 @@ const_def
 
 %%
 
-void yyerror(YYLTYPE * loc, struct kafel_ctxt* ctxt, yyscan_t scanner,
-             const char *msg) {
+void yyerror(YYLTYPE * loc, struct kafel_ctxt* ctxt,
+             __attribute__((unused)) yyscan_t scanner, const char *msg) {
```
Comment (happyCoder92) [inline src/parser.y:422]: just drop the parameter name instead

Comment (foutrelis) [reply src/parser.y:422]: I believe that only works in C++. Leaving out the name in C results in `error: parameter name omitted`.

Comment (happyCoder92) [reply src/parser.y:422]: Oh, right... This is C :-)
`(void)scanner;` might be a bit more portable, but the attribute is fine too here I guess.

Comment (foutrelis) [reply src/parser.y]: Better portability is always a plus and it is also what the YYUSE macro did. I have updated the PR to implement your suggestion. :)

**Comment by happyCoder92** [comment]
Thanks for the fix! :)
